### ISSUE TITLE
Banner/Logo not centered

### ISSUE THREAD

**Issue by hfroese** [disroot/dishub-themes#1]
The banner/logo is not centered. Adding apps moves the banner to the right.

![20180527-2150](https://user-images.githubusercontent.com/1968490/40590072-001cbebc-61f9-11e8-94c3-ab01cdbef699.jpg)

**Comment by antil0pa** [comment]
fixed

**Comment by hfroese** [comment]
Not fixed yet. It's not centered:

![20180528-0024](https://user-images.githubusercontent.com/1968490/40591243-a365b8da-620d-11e8-8f1a-6e8063f0e98c.jpg)

**Comment by antil0pa** [comment]
ah true. just fixed the moving while adding apps part.. will look into it still. Thanks.

**Comment by antil0pa** [comment]
Please try now.

**Comment by hfroese** [comment]
Works now,  but banner links are not working anymore.

**Comment by antil0pa** [comment]
Can you point me to the links that don't work? As far as i can see they all seem to work..

**Comment by hfroese** [comment]
Console output:

`Laden fehlgeschlagen für das <script> mit der Quelle "https://code.simplesvg.com/1/1.0.0-beta5/simple-svg.min.js".


Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf https://code.simplesvg.com/1/1.0.0-beta5/simple-svg.min.js blockiert ("script-src").`

**Comment by hfroese** [comment]
https://node.hfrc.de/

Both are banner links

**Comment by antil0pa** [comment]
simplesvg is not used for anything, I will remove it from the code.

As for the banner links - you mean the search button and the hamburger menu? They work on my side. Can you try and see if it works with a different browser?

**Comment by hfroese** [comment]
Nope. I mean the centered links like  `HFRC - My Personal Fediverse Node` and `My Notifications`   both are links and they still work in redbasic.


`<i class="fa fa-hubzilla"></i>&nbsp;<a href="/network?f=&order=post">HFRC - My Personal Fediverse Node</a> &bull; <a target="_blank" href="https://node.hfrc.de/my-notifications.php">My Notifications</a>`

**Comment by antil0pa** [comment]
ah got it :P will look into it in a bit

**Comment by antil0pa** [comment]
Please check now

**Comment by hfroese** [comment]
Works again. Thanks 👍
